### ISSUE TITLE
bug: android app not respecting --application-id  

### ISSUE THREAD

**Issue by egyleader** [VeryGoodOpenSource/very_good_core#277]
**Description**
when creating new flutter app using `very_good create ` and specifying name  + application-id parameteres the android app generate application id based on the name parameter instead of respecting the `--application-id` parameter provided

**Steps To Reproduce**
1. create new project using command :

```dart
very_good create flutter_app project_name --org com.example --application-id  com.example.name 
```

**Expected Behavior**
android & ios apps with id's `com.example.name`

**Actual Behavior**
android project with id : `com.example.project_name`
 
**Additional Context**
resulting error : 
```dart
Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-39 value=(com.example.project_name)
	does not match the module's namespace (com.example.name).
```

**Comment by alestiago** [comment]
Hi @egyleader 👋 ! Thanks for opening this issue 💙 

We're moving this repository to [Very Good Templates](https://github.com/VeryGoodOpenSource/very_good_templates). Hence, I'm closing this issue. Feel free to open a new issue there. Otherwise, I'll reopen it there once I verify, by reproducing, that the issue still persists.
