### ISSUE TITLE
bug: RunnerTests is not linked to the ios project

### ISSUE THREAD

**Issue by yuruyuri16** [VeryGoodOpenSource/very_good_core#292]
**Description**
The Podfile expects a RunnerTests directory. 
It was added but I believe it was not linked to the ios project. Therefore, cocoapods cannot find it.

**Steps To Reproduce**

1. Create a flutter app
2. Add a package that produces a Podfile, (e.g., firebase_core)
3. Run app

**Expected Behavior**
The app should run normally.

**Additional Context**
This error was supposed to be fixed in version 0.16.0 but that problem persists.

**Comment by alestiago** [comment]
Hi @yuruyuri16 👋 ! Thanks for opening this issue 💙 

We're moving this repository to [Very Good Templates](https://github.com/VeryGoodOpenSource/very_good_templates). Hence, I'm closing this issue. Feel free to open a new issue there. Otherwise, I'll reopen it there once I verify, by reproducing, that the issue still persists.
