### ISSUE TITLE
fix: gradlew is not executable after genration

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_core#295]
**Description**

The generated `gradlew` file has no execute permission after generation, even though the one under `src/` is executable. 

**Additional Context**

https://github.com/felangel/mason/issues/1120

**Comment by alestiago** [comment]
Hi @renancaraujo 👋 ! Thanks for opening this issue 💙 

We're moving this repository to [Very Good Templates](https://github.com/VeryGoodOpenSource/very_good_templates). Hence, I'm closing this issue. Feel free to open a new issue there. Otherwise, I'll reopen it there once I verify, by reproducing, that the issue still persists.
